simulator: ngspice
corners:
  - name: TT
    temperature: 25
    voltage: 1.8
cells:
  inverter:
    netlist: "cells/inverter.spice"
    models:
      - "sky130A/libs.tech/ngspice/sky130.lib.spice tt"
    data_slews: [0.01, 0.05, 0.1, 0.2]
    loads: [0.001, 0.005, 0.01, 0.05]
    functions:
      - "OUT = !IN"
